[phases.setup]
nixPkgs = ["tesseract", "python311", "ffmpeg", "glib", "libGL"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "pip install opencv-python-headless"
]

[start]
cmd = "python bot.py"
